base = "materials::state"

[[rulesets]]
name = "adjective"
[rulesets.rules]
"{shared}" = "{shared}"

[[rulesets]]
name = "shared"
[rulesets.rules]
"{shared::main}" = "{shared::main}"

[[rulesets]]
name = "shared::main"
[rulesets.rules]
"acacia" = "アカシア材"
"adamantine" = "精金"
"adder man venom" = "アダー人の毒"
"adder venom" = "アダーの毒"
"alabaster" = "雪花石膏"
"alder" = "ハンノキ材"
"alexandrite" = "アレキサンドライト"
"almandine" = "アルマンディン"
"almond wood" = "アーモンド材"
"alpaca cheese" = "アルパカチーズ"
"alpaca's milk" = "アルパカ乳"
"aluminum" = "アルミニウム"
"alunite" = "明礬石"
"amber" = "琥珀"
"amber opal" = "アンバーオパール"
"amethyst" = "アメシスト"
"andesite" = "安山岩"
"anhydrite" = "硬石膏"
"antler" = "枝角"
"apple cider" = "リンゴシードル"
"apple wood" = "リンゴ材"
"apricot wine" = "アンズワイン"
"apricot wood" = "アンズ材"
"aquamarine" = "アクアマリン"
"artichoke wine" = "アーティチョークワイン"
"ash" = "トネリコ材"
"ash glaze" = "灰釉"
"aventurine" = "アベンチュリン"
"avocado wood" = "アボカド材"
"banana beer" = "バナナビール"
"banded agate" = "縞瑪瑙"
"bandfire opal" = "バンドファイアオパール"
"bark scorpion man venom" = "バークスコーピオン人の毒"
"bark scorpion venom" = "バークスコーピオンの毒"
"barley flour" = "大麦粉"
"barley wine" = "バーレイワイン"
"basalt" = "玄武岩"
"bauxite" = "ボーキサイト"
"bayberry wine" = "ベイベリーワイン"
"bayberry wood" = "ベイベリー材"
"beetroot wine" = "ビーツワイン"
"bilberry wine" = "ビルベリーワイン"
"billon" = "ビロン"
"bismuth" = "ビスマス"
"bismuth bronze" = "ビスマス青銅"
"bismuthinite" = "輝蒼鉛鉱"
"bitter orange wood" = "ダイダイ材"
"bituminous coal" = "瀝青炭"
"blackberry wine" = "ブラックベリーワイン"
"black bronze" = "赤銅"
"black-cap" = "黒笠材"
"black diamond" = "ブラックダイヤモンド"
"black mamba man venom" = "ブラックマンバ人の毒"
"black mamba venom" = "ブラックマンバの毒"
"black opal" = "ブラックオパール"
"black pyrope" = "黒苦礬柘榴石"
"black sand" = "黒砂"
"black zircon" = "ブラックジルコン"
"blood" = "血液"
"blood amaranth beer" = "スギモリゲイトウビール"
"blood amaranth flour" = "スギモリゲイトウ粉"
"bloodstone" = "血石"
"blood thorn" = "血棘材"
"blueberry wine" = "ブルーベリーワイン"
"blue diamond" = "ブルーダイヤモンド"
"blue garnet" = "青柘榴石"
"blue jade" = "青翡翠"
"bone" = "骨"
"bone meal" = "骨粉"
"bone opal" = "ボーンオパール"
"borax" = "ホウ砂"
"brain" = "脳"
"brass" = "黄銅"
"brimstone" = "硫黄"
"bronze" = "青銅"
"brown jasper" = "褐色碧玉"
"brown recluse spider man venom" = "ドクイトグモ人の毒"
"brown recluse spider venom" = "ドクイトグモの毒"
"brown zircon" = "ブラウンジルコン"
"buckwheat beer" = "ソバビール"
"buckwheat flour" = "ソバ粉"
"bud" = "蕾"
"bumblebee honey" = "マルハナバチの蜂蜜"
"bumblebee mead" = "マルハナバチの蜂蜜酒"
"bumblebee royal jelly" = "マルハナバチのローヤルゼリー"
"bumblebee venom" = "マルハナバチの毒"
"bumblebee wax" = "マルハナバチの蜜蝋"
"bumblebee wax cake" = "マルハナバチの蜜蝋ケーキ"
"bushmaster man venom" = "ブッシュマスター人の毒"
"bushmaster venom" = "ブッシュマスターの毒"
"cacao wood" = "カカオ材"
"calcareous ooze" = "石灰質軟泥"
"calcite" = "方解石"
"candlenut" = "ククイ材"
"carambola wine" = "スターフルーツワイン"
"carambola wood" = "スターフルーツ材"
"carnelian" = "カーネリアン"
"carrot wine" = "ニンジンワイン"
"cashew wood" = "カシューナッツ材"
"cassava beer" = "キャッサバビール"
"cassiterite" = "錫石"
"cat's eye" = "キャッツアイ"
"cave blob fluid" = "洞塊液"
"cave floater gas" = "洞浮毒気"
"cave floater juice" = "洞浮液"
"cave spider venom" = "洞窟グモの毒"
"cedar" = "スギ材"
"chalk" = "白亜"
"cherry opal" = "チェリーオパール"
"cherry wine" = "サクランボワイン"
"cherry wood" = "サクラ材"
"chert" = "チャート"
"chestnut" = "クリ材"
"chitin" = "キチン"
"chromite" = "クロム鉄鉱"
"chrysoberyl" = "クリソベリル"
"chrysocolla" = "クリソコラ"
"chrysoprase" = "クリソプレーズ"
"cinnabar" = "辰砂"
"cinnamon grossular" = "ヘソナイト"
"citrine" = "シトリン"
"citron wood" = "シトロン材"
"claro opal" = "クラロオパール"
"clay" = "粘土"
"clay loam" = "埴壌土"
"claystone" = "粘土岩"
"clear diamond" = "クリアダイヤモンド"
"clear garnet" = "クリアガーネット"
"clear glass" = "透明ガラス"
"clear tourmaline" = "クリアトルマリン"
"clear zircon" = "クリアジルコン"
"coal" = "石炭"
"coal slush" = "石炭泥"
"cobaltite" = "輝コバルト鉱"
"coconut palm" = "ココヤシ材"
"coffee wood" = "コーヒーノキ材"
"condensed iron man gas" = "凝縮鉄人ガス"
"conglomerate" = "礫岩"
"copper" = "銅"
"copperhead snake man venom" = "カパーヘッド人の毒"
"copperhead snake venom" = "カパーヘッドの毒"
"coral" = "サンゴ"
"corrupted blood" = "穢れた血"
"cotton" = "綿"
"cotton seed" = "綿実"
"cottonseed oil" = "綿実油"
"cottonseed oil soap" = "綿実油石鹸"
"cow cheese" = "牛乳チーズ"
"cow's milk" = "牛乳"
"cranberry wine" = "クランベリーワイン"
"cryolite" = "氷晶石"
"crystal glass" = "クリスタルガラス"
"crystal opal" = "クリスタルオパール"
"custard-apple cider" = "チェリモヤシードル"
"custard-apple wood" = "チェリモヤ材"
"cuttlefish ink" = "コウイカの墨"
"cuttlefish man ink" = "コウイカ人の墨"
"dacite" = "デイサイト"
"date palm wood" = "ナツメヤシ材"
"date wine" = "デーツワイン"
"demantoid" = "デマントイド"
"dendritic agate" = "デンドリティックアゲート"
"desert lime wood" = "デザートライム材"
"dimple dye" = "エクボタケ染料"
"diorite" = "閃緑岩"
"dirt" = "土"
"dolomite" = "苦灰石"
"donkey cheese" = "ロバ乳チーズ"
"donkey's milk" = "ロバ乳"
"durian wine" = "ドリアンワイン"
"durian wood" = "ドリアン材"
"dwarven ale" = "ドワーフのエール"
"dwarven beer" = "ドワーフのビール"
"dwarven cheese" = "ドワーフのチーズ"
"dwarven milk" = "ドワーフの乳"
"dwarven rum" = "ドワーフのラム"
"dwarven sugar" = "ドワーフの砂糖"
"dwarven syrup" = "ドワーフのシロップ"
"dwarven wheat flour" = "ドワーフ小麦粉"
"dwarven wine" = "ドワーフのワイン"
"earthenware" = "土器"
"eggshell" = "卵殻"
"egg white" = "卵白"
"egg yolk" = "卵黄"
"electrum" = "エレクトラム"
"emerald" = "エメラルド"
"emerald dye" = "エメラルド染料"
"eye tissue" = "眼組織"
"faint yellow diamond" = "フェイントイエローダイヤモンド"
"feather" = "羽毛"
"feather wood" = "羽毛樹材"
"fiber" = "繊維"
"filth" = "汚物"
"filth slush" = "汚物泥"
"fine pewter" = "ファインピューター"
"finger lime wood" = "フィンガーライム材"
"finger millet beer" = "シコクビエビール"
"finger millet flour" = "シコクビエ粉"
"fire agate" = "ファイアアゲート"
"fire clay" = "耐火粘土"
"iron" = "鉄"
"steel" = "鋼"
"fire opal" = "ファイアオパール"
"fisher berry wine" = "漁師果ワイン"
"flames" = "炎"
"flax flour" = "亜麻粉"
"flax seed" = "亜麻種子"
"flesh" = "肉"
"flower" = "花"
"fluff" = "綿毛"
"fonio beer" = "フォニオビール"
"fonio flour" = "フォニオ粉"
"fortification agate" = "フォルティフィケーションアゲート"
"foxtail millet beer" = "アワビール"
"foxtail millet flour" = "アワ粉"
"fruit" = "果実"
"fungiwood" = "菌木材"
"fur" = "毛皮"
"gabbro" = "斑れい岩"
"galena" = "方鉛鉱"
"garnierite" = "珪ニッケル鉱"
"giant adder venom" = "巨大アダーの毒"
"giant bark scorpion venom" = "巨大バークスコーピオンの毒"
"giant black mamba venom" = "巨大ブラックマンバの毒"
"giant brown recluse spider venom" = "巨大ドクイトグモの毒"
"giant bushmaster venom" = "巨大ブッシュマスターの毒"
"giant cave spider venom" = "巨大洞窟グモの毒"
"giant copperhead snake venom" = "巨大カパーヘッドの毒"
"giant cuttlefish ink" = "巨大コウイカの墨"
"giant gila monster venom" = "巨大アメリカドクトカゲの毒"
"giant kangaroo cheese" = "巨大カンガルー乳チーズ"
"giant kangaroo's milk" = "巨大カンガルー乳"
"giant king cobra venom" = "巨大キングコブラの毒"
"giant octopus ink" = "巨大タコの墨"
"giant one-humped camel cheese" = "巨大ヒトコブラクダ乳チーズ"
"giant one-humped camel's milk" = "巨大ヒトコブラクダ乳"
"giant platypus venom" = "巨大カモノハシの毒"
"giant rattlesnake venom" = "巨大ガラガラヘビの毒"
"giant squid ink" = "巨大イカの墨"
"giant tapir cheese" = "巨大バク乳チーズ"
"giant tapir's milk" = "巨大バク乳"
"giant two-humped camel cheese" = "巨大フタコブラクダ乳チーズ"
