base = "materials::state"

[[rulesets]]
[rulesets.rules]
"gold dust" = "金粉"
"metal" = "金属"
"native gold dust" = "自然金粉"
"fat" = "脂肪"
"grease" = "油脂"
"cartilage" = "軟骨"
"cheese" = "チーズ"
"wood" = "木材"
"sponge" = "海綿"
"saguaro rib wood" = "サワロ肋材"
"oak" = "オーク"
"birch" = "カバノキ"
"{shared}" = "{shared}"

[[rulesets]]
name = "adjective"
[rulesets.rules]
"fatty" = "脂肪"
"greasy" = "油脂"
"cartilaginous" = "軟骨"
"cheesy" = "チーズ"
"wooden" = "木材"
"spongy" = "海綿"
"saguaro rib" = "サワロ肋材"
"oaken" = "オーク材"
"birchen" = "カバ材"
"ashen" = "トネリコ材"
"{shared}" = "{shared}"

[[rulesets]]
name = "shared"
[rulesets.rules]
"{shared::main}" = "{shared::main}"

[[rulesets]]
name = "shared::main"
[rulesets.rules]
"acacia" = "アカシア材"
"adamantine" = "精金"
"adder man venom" = "アダー人の毒"
"adder venom" = "アダーの毒"
"alabaster" = "雪花石膏"
"alder" = "ハンノキ材"
"alexandrite" = "アレキサンドライト"
"almandine" = "アルマンディン"
"almond wood" = "アーモンド材"
"alpaca cheese" = "アルパカチーズ"
"alpaca's milk" = "アルパカ乳"
"aluminum" = "アルミニウム"
"alunite" = "明礬石"
"amber" = "琥珀"
"amber opal" = "アンバーオパール"
"amethyst" = "アメシスト"
"andesite" = "安山岩"
"anhydrite" = "硬石膏"
"antler" = "枝角"
"apple cider" = "リンゴシードル"
"apple wood" = "リンゴ材"
"apricot wine" = "アンズワイン"
"apricot wood" = "アンズ材"
"aquamarine" = "アクアマリン"
"artichoke wine" = "アーティチョークワイン"
"ash" = "灰"
"ash glaze" = "灰釉"
"aventurine" = "アベンチュリン"
"avocado wood" = "アボカド材"
"banana beer" = "バナナビール"
"banded agate" = "縞瑪瑙"
"bandfire opal" = "バンドファイアオパール"
"bark scorpion man venom" = "バークスコーピオン人の毒"
"bark scorpion venom" = "バークスコーピオンの毒"
"barley flour" = "大麦粉"
"barley wine" = "バーレイワイン"
"basalt" = "玄武岩"
"bauxite" = "ボーキサイト"
"bayberry wine" = "ベイベリーワイン"
"bayberry wood" = "ベイベリー材"
"beetroot wine" = "ビーツワイン"
"bilberry wine" = "ビルベリーワイン"
"billon" = "ビロン"
"bismuth" = "ビスマス"
"bismuth bronze" = "ビスマス青銅"
"bismuthinite" = "輝蒼鉛鉱"
"bitter orange wood" = "ダイダイ材"
"bituminous coal" = "瀝青炭"
"blackberry wine" = "ブラックベリーワイン"
"black bronze" = "赤銅"
"black-cap" = "黒笠材"
"black diamond" = "ブラックダイヤモンド"
"black mamba man venom" = "ブラックマンバ人の毒"
"black mamba venom" = "ブラックマンバの毒"
"black opal" = "ブラックオパール"
"black pyrope" = "黒苦礬柘榴石"
"black sand" = "黒砂"
"black zircon" = "ブラックジルコン"
"blood" = "血液"
"blood amaranth beer" = "スギモリゲイトウビール"
"blood amaranth flour" = "スギモリゲイトウ粉"
"bloodstone" = "血石"
"blood thorn" = "血棘材"
"blueberry wine" = "ブルーベリーワイン"
"blue diamond" = "ブルーダイヤモンド"
"blue garnet" = "青柘榴石"
"blue jade" = "青翡翠"
"bone" = "骨"
"bone meal" = "骨粉"
"bone opal" = "ボーンオパール"
"borax" = "ホウ砂"
"brain" = "脳"
"brass" = "黄銅"
"brimstone" = "硫黄"
"bronze" = "青銅"
"brown jasper" = "褐色碧玉"
"brown recluse spider man venom" = "ドクイトグモ人の毒"
"brown recluse spider venom" = "ドクイトグモの毒"
"brown zircon" = "ブラウンジルコン"
"buckwheat beer" = "ソバビール"
"buckwheat flour" = "ソバ粉"
"bud" = "蕾"
"bumblebee honey" = "マルハナバチの蜂蜜"
"bumblebee mead" = "マルハナバチの蜂蜜酒"
"bumblebee royal jelly" = "マルハナバチのローヤルゼリー"
"bumblebee venom" = "マルハナバチの毒"
"bumblebee wax" = "マルハナバチの蜜蝋"
"bumblebee wax cake" = "マルハナバチの蜜蝋ケーキ"
"bushmaster man venom" = "ブッシュマスター人の毒"
"bushmaster venom" = "ブッシュマスターの毒"
"cacao wood" = "カカオ材"
"calcareous ooze" = "石灰質軟泥"
"calcite" = "方解石"
"candlenut" = "ククイ材"
"carambola wine" = "スターフルーツワイン"
"carambola wood" = "スターフルーツ材"
"carnelian" = "カーネリアン"
"carrot wine" = "ニンジンワイン"
"cashew wood" = "カシューナッツ材"
"cassava beer" = "キャッサバビール"
"cassiterite" = "錫石"
"cat's eye" = "キャッツアイ"
"cave blob fluid" = "洞塊液"
"cave floater gas" = "洞浮毒気"
"cave floater juice" = "洞浮液"
"cave spider venom" = "洞窟グモの毒"
"cedar" = "スギ材"
"chalk" = "白亜"
"cherry opal" = "チェリーオパール"
"cherry wine" = "サクランボワイン"
"cherry wood" = "サクラ材"
"chert" = "チャート"
"chestnut" = "クリ材"
"chitin" = "キチン"
"chromite" = "クロム鉄鉱"
"chrysoberyl" = "クリソベリル"
"chrysocolla" = "クリソコラ"
"chrysoprase" = "クリソプレーズ"
"cinnabar" = "辰砂"
"cinnamon grossular" = "ヘソナイト"
"citrine" = "シトリン"
"citron wood" = "シトロン材"
"claro opal" = "クラロオパール"
"clay" = "粘土"
"clay loam" = "埴壌土"
"claystone" = "粘土岩"
"clear diamond" = "クリアダイヤモンド"
"clear garnet" = "クリアガーネット"
"clear glass" = "透明ガラス"
"clear tourmaline" = "クリアトルマリン"
"clear zircon" = "クリアジルコン"
"coal" = "石炭"
"coal slush" = "石炭泥"
"cobaltite" = "輝コバルト鉱"
"coconut palm" = "ココヤシ材"
"coffee wood" = "コーヒーノキ材"
"condensed iron man gas" = "凝縮鉄人ガス"
"conglomerate" = "礫岩"
"copper" = "銅"
"copperhead snake man venom" = "カパーヘッド人の毒"
"copperhead snake venom" = "カパーヘッドの毒"
"coral" = "サンゴ"
"corrupted blood" = "穢れた血"
"cotton" = "綿"
"cotton seed" = "綿実"
"cottonseed oil" = "綿実油"
"cottonseed oil soap" = "綿実油石鹸"
"cow cheese" = "牛乳チーズ"
"cow's milk" = "牛乳"
"cranberry wine" = "クランベリーワイン"
"cryolite" = "氷晶石"
"crystal glass" = "クリスタルガラス"
"crystal opal" = "クリスタルオパール"
"custard-apple cider" = "チェリモヤシードル"
"custard-apple wood" = "チェリモヤ材"
"cuttlefish ink" = "コウイカの墨"
"cuttlefish man ink" = "コウイカ人の墨"
"dacite" = "デイサイト"
"date palm wood" = "ナツメヤシ材"
"date wine" = "デーツワイン"
"demantoid" = "デマントイド"
"dendritic agate" = "デンドリティックアゲート"
"desert lime wood" = "デザートライム材"
"dimple dye" = "エクボタケ染料"
"diorite" = "閃緑岩"
"dirt" = "土"
"dolomite" = "苦灰石"
"donkey cheese" = "ロバ乳チーズ"
"donkey's milk" = "ロバ乳"
"durian wine" = "ドリアンワイン"
"durian wood" = "ドリアン材"
"dwarven ale" = "ドワーフのエール"
"dwarven beer" = "ドワーフのビール"
"dwarven cheese" = "ドワーフのチーズ"
"dwarven milk" = "ドワーフの乳"
"dwarven rum" = "ドワーフのラム"
"dwarven sugar" = "ドワーフの砂糖"
"dwarven syrup" = "ドワーフのシロップ"
"dwarven wheat flour" = "ドワーフ小麦粉"
"dwarven wine" = "ドワーフのワイン"
"earthenware" = "土器"
"eggshell" = "卵殻"
"egg white" = "卵白"
"egg yolk" = "卵黄"
"electrum" = "エレクトラム"
"emerald" = "エメラルド"
"emerald dye" = "エメラルド染料"
"eye tissue" = "眼組織"
"faint yellow diamond" = "フェイントイエローダイヤモンド"
"feather" = "羽毛"
"feather wood" = "羽毛樹材"
"fiber" = "繊維"
"filth" = "汚物"
"filth slush" = "汚物泥"
"fine pewter" = "ファインピューター"
"finger lime wood" = "フィンガーライム材"
"finger millet beer" = "シコクビエビール"
"finger millet flour" = "シコクビエ粉"
"fire agate" = "ファイアアゲート"
"fire clay" = "耐火粘土"
"iron" = "鉄"
"steel" = "鋼"
"fire opal" = "ファイアオパール"
"fisher berry wine" = "漁師果ワイン"
"flames" = "炎"
"flax flour" = "亜麻粉"
"flax seed" = "亜麻種子"
"flesh" = "肉"
"flower" = "花"
"fluff" = "綿毛"
"fonio beer" = "フォニオビール"
"fonio flour" = "フォニオ粉"
"fortification agate" = "フォルティフィケーションアゲート"
"foxtail millet beer" = "アワビール"
"foxtail millet flour" = "アワ粉"
"fruit" = "果実"
"fungiwood" = "菌木材"
"fur" = "毛皮"
"gabbro" = "斑れい岩"
"galena" = "方鉛鉱"
"garnierite" = "珪ニッケル鉱"
"giant adder venom" = "巨大アダーの毒"
"giant bark scorpion venom" = "巨大バークスコーピオンの毒"
"giant black mamba venom" = "巨大ブラックマンバの毒"
"giant brown recluse spider venom" = "巨大ドクイトグモの毒"
"giant bushmaster venom" = "巨大ブッシュマスターの毒"
"giant cave spider venom" = "巨大洞窟グモの毒"
"giant copperhead snake venom" = "巨大カパーヘッドの毒"
"giant cuttlefish ink" = "巨大コウイカの墨"
"giant gila monster venom" = "巨大ドクトカゲの毒"
"giant kangaroo cheese" = "巨大カンガルー乳チーズ"
"giant kangaroo's milk" = "巨大カンガルー乳"
"giant king cobra venom" = "巨大キングコブラの毒"
"giant octopus ink" = "巨大タコの墨"
"giant one-humped camel cheese" = "巨大ヒトコブラクダ乳チーズ"
"giant one-humped camel's milk" = "巨大ヒトコブラクダ乳"
"giant platypus venom" = "巨大カモノハシの毒"
"giant rattlesnake venom" = "巨大ガラガラヘビの毒"
"giant squid ink" = "巨大イカの墨"
"giant tapir cheese" = "巨大バク乳チーズ"
"giant tapir's milk" = "巨大バク乳"
"giant two-humped camel cheese" = "巨大フタコブラクダ乳チーズ"
"giant two-humped camel's milk" = "巨大フタコブラクダ乳"
"gila monster man venom" = "ドクトカゲ人の毒"
"gila monster venom" = "ドクトカゲの毒"
"ginkgo wood" = "イチョウ材"
"gizzard tissue" = "砂嚢組織"
"glumprong" = "紫影木材"
"gneiss" = "片麻岩"
"gnomeblight" = "小人枯毒"
"goat cheese" = "山羊乳チーズ"
"goat's milk" = "山羊乳"
"goblin-cap" = "紅傘茸材"
"gold" = "金"
"golden beryl" = "ゴールデンベリル"
"golden salve" = "黄金膏"
"gold opal" = "ゴールドオパール"
"goo" = "粘血"
"goshenite" = "ゴシェナイト"
"granite" = "花崗岩"
"graphite" = "石墨"
"gray chalcedony" = "グレーカルセドニー"
"green diamond" = "グリーンダイヤモンド"
"green glass" = "緑色ガラス"
"green jade" = "グリーンジェイド"
"green tourmaline" = "グリーントルマリン"
"green zircon" = "グリーンジルコン"
"grime" = "汚泥"
"guava wine" = "グアバワイン"
"guava wood" = "グアバ材"
"gut" = "腸"
"gutter cruor" = "溝血酒"
"gypsum" = "石膏"
"gypsum plaster" = "石膏プラスター"
"hair" = "毛"
"hard wheat beer" = "硬質小麦ビール"
"hard wheat flour" = "硬質小麦粉"
"harlequin opal" = "ハーレクインオパール"
"hazel wood" = "ハシバミ材"
"heart tissue" = "心臓組織"
"heliodor" = "ヘリオドール"
"helmet snake venom" = "兜蛇の毒"
"hematite" = "赤鉄鉱"
"hemp" = "大麻"
"hemp flour" = "大麻粉"
"hemp seed" = "大麻種子"
"hempseed oil" = "大麻種子油"
"hempseed oil soap" = "大麻種子油石鹸"
"highwood" = "高天木材"
"honey bee honey" = "ミツバチの蜂蜜"
"honey bee royal jelly" = "ミツバチのローヤルゼリー"
"honey bee venom" = "ミツバチの毒"
"honey bee wax" = "ミツバチの蜜蝋"
"honey bee wax cake" = "ミツバチの蜜蝋ケーキ"
"honey yellow beryl" = "ハニーイエローベリル"
"hoof" = "蹄"
"horn" = "角"
"hornblende" = "角閃石"
"horn silver" = "角銀鉱"
"horse cheese" = "馬乳チーズ"
"horse's milk" = "馬乳"
"ice" = "氷"
"ichor" = "血体腔液"
"ilmenite" = "チタン鉄鉱"
"indigo tourmaline" = "インディゴトルマリン"
"iron man gas" = "鉄人ガス"
"ivory" = "象牙"
"jasper opal" = "ジャスパーオパール"
"jelly opal" = "ジェリーオパール"
"jet" = "黒玉"
"jute" = "ジュート"
"kangaroo cheese" = "カンガルー乳チーズ"
"kangaroo man cheese" = "カンガルー人乳チーズ"
"kangaroo man's milk" = "カンガルー人乳"
"kangaroo's milk" = "カンガルー乳"
"kaniwa beer" = "カニワビール"
"kaniwa flour" = "カニワ粉"
"kaolinite" = "カオリン石"
"kapok" = "カポック材"
"kenaf" = "ケナフ"
"kenaf seed" = "ケナフ種子"
"kenaf seed oil" = "ケナフ種子油"
"kenaf seed oil soap" = "ケナフ種子油石鹸"
"kidney tissue" = "腎臓組織"
"kimberlite" = "キンバーライト"
"king cobra man venom" = "キングコブラ人の毒"
"king cobra venom" = "キングコブラの毒"
"kumquat wood" = "キンカン材"
"kunzite" = "クンツァイト"
"lace agate" = "レースアゲート"
"lapis lazuli" = "ラピスラズリ"
"larch" = "カラマツ材"
"lavender jade" = "ラベンダージェイド"
"lay pewter" = "ピューター"
"lead" = "鉛"
"leaf" = "葉"
"leather" = "革"
"levin opal" = "レヴィンオパール"
"light yellow diamond" = "ライトイエローダイヤモンド"
"lignite" = "褐炭"
"limestone" = "石灰岩"
"lime wood" = "ライム材"
"limonite" = "褐鉄鉱"
"linen" = "亜麻布"
"linseed oil" = "亜麻仁油"
"linseed oil soap" = "亜麻仁油石鹸"
"liquid fire" = "液体火"
"liver tissue" = "肝臓組織"
"llama cheese" = "ラマ乳チーズ"
"llama's milk" = "ラマ乳"
"loam" = "壌土"
"loamy sand" = "壌質砂"
"Longland beer" = "長原草ビール"
"Longland flour" = "長原草粉"
"lung tissue" = "肺組織"
"lychee wine" = "ライチワイン"
"lychee wood" = "ライチ材"
"lye" = "灰汁"
"lye slush" = "灰汁泥"
"macadamia wood" = "マカダミア材"
"magma" = "マグマ"
"magnetite" = "磁鉄鉱"
"mahogany" = "マホガニー材"
"maize beer" = "トウモロコシビール"
"maize flour" = "トウモロコシ粉"
"malachite" = "孔雀石"
"mango wine" = "マンゴーワイン"
"mango wood" = "マンゴー材"
"mangrove" = "マングローブ材"
"maple" = "カエデ材"
"marble" = "大理石"
"marcasite" = "白鉄鉱"
"mead" = "蜂蜜酒"
"melanite" = "メラナイト"
"mica" = "雲母"
"microcline" = "微斜長石"
"milk of lime" = "石灰乳"
"milk opal" = "ミルクオパール"
"milk quartz" = "ミルキークォーツ"
"mog juice" = "沼跳虫汁"
"moonstone" = "ムーンストーン"
"morganite" = "モルガナイト"
"morion" = "モリオン"
"moss agate" = "モスアゲート"
"moss opal" = "モスオパール"
"mud" = "泥"
"mudstone" = "泥岩"
"muscle" = "筋肉"
"mushroom" = "キノコ"
"nail" = "爪"
"native aluminum" = "自然アルミニウム"
"native copper" = "自然銅"
"native gold" = "自然金"
"native platinum" = "自然白金"
"native silver" = "自然銀"
"nervous tissue" = "神経組織"
"nether-cap" = "冥冷茸材"
"nickel" = "ニッケル"
"nickel silver" = "洋白"
"oat flour" = "オート麦粉"
"obsidian" = "黒曜石"
"octopus ink" = "タコの墨"
"octopus man ink" = "タコ人の墨"
"olive fruit" = "オリーブ果実"
"olive oil" = "オリーブ油"
"olive oil soap" = "オリーブ油石鹸"
"olive pomace" = "オリーブ搾りかす"
"olive wood" = "オリーブ材"
"olivine" = "かんらん石"
"one-humped camel cheese" = "ヒトコブラクダ乳チーズ"
"one-humped camel man cheese" = "ヒトコブラクダ人乳チーズ"
"one-humped camel man's milk" = "ヒトコブラクダ人乳"
"one-humped camel's milk" = "ヒトコブラクダ乳"
"onyx" = "オニキス"
"onyx opal" = "オニキスオパール"
"orange wood" = "オレンジ材"
"orpiment" = "雌黄"
"orthoclase" = "正長石"
"pancreatic tissue" = "膵組織"
"papaya wine" = "パパイヤワイン"
"papaya wood" = "パパイヤ材"
"papyrus" = "パピルス"
"paradise nut wood" = "パラダイスナッツ材"
"parchment" = "羊皮紙"
"parsnip wine" = "パースニップワイン"
"passion fruit wine" = "パッションフルーツワイン"
"peach cider" = "モモシードル"
"peach wood" = "モモ材"
"pearlash" = "真珠灰"
"pearl millet beer" = "トウジンビエビール"
"pearl millet flour" = "トウジンビエ粉"
"pear wood" = "ナシ材"
"peat" = "泥炭"
"pecan wood" = "ペカン材"
"pelagic clay" = "遠洋性粘土"
"pendant amaranth beer" = "ヒモゲイトウビール"
"pendant amaranth flour" = "ヒモゲイトウ粉"
"periclase" = "ペリクレース"
"peridot" = "ペリドット"
"perry" = "ペリー"
"persimmon wine" = "カキワイン"
"persimmon wood" = "柿材"
"petrified wood" = "珪化木"
"phantom spider venom" = "幻影蜘蛛の毒"
"phyllite" = "千枚岩"
"picture jasper" = "ピクチャージャスパー"
"pig cheese" = "豚乳チーズ"
"pig iron" = "銑鉄"
"pig's milk" = "豚乳"
"pig tail" = "豚尾草"
"pine" = "松材"
"pineapple opal" = "パイナップルオパール"
"pineapple wine" = "パイナップルワイン"
"pinfire opal" = "ピンファイアオパール"
"pink garnet" = "ピンクガーネット"
"pink jade" = "ピンクジェード"
"pink tourmaline" = "ピンクトルマリン"
"pipe opal" = "パイプオパール"
"pitchblende" = "瀝青ウラン鉱"
"plant" = "植物"
"platinum" = "白金"
"platypus man venom" = "カモノハシ人の毒"
"platypus venom" = "カモノハシの毒"
"plume agate" = "プルームアゲート"
"plump helmet man tissue" = "肉厚兜茸人組織"
"plum wine" = "プラムワイン"
"plum wood" = "スモモ材"
"pomegranate wine" = "ザクロワイン"
"pomegranate wood" = "ザクロ材"
"pomelo wood" = "ザボン材"
"porcelain" = "磁器"
"potash" = "カリ"
"potash slush" = "カリ泥"
"potato wine" = "ジャガイモワイン"
"prase" = "プラース"
"prase opal" = "プラースオパール"
"precious fire opal" = "プレシャスファイアオパール"
"prickle berry wine" = "プリックルベリーワイン"
"puddingstone" = "プディングストーン"
"pudge" = "紫脂"
"purple amaranth beer" = "紫アマランサスビール"
"purple amaranth flour" = "紫アマランサス粉"
"purple spinel" = "紫スピネル"
"pus" = "膿"
"pyrite" = "黄鉄鉱"
"pyrolusite" = "軟マンガン鉱"
"quartzite" = "珪岩"
"quicklime" = "生石灰"
"quinoa beer" = "キヌアビール"
"quinoa flour" = "キヌア粉"
"radish wine" = "ラディッシュワイン"
"rambutan wine" = "ランブータンワイン"
"rambutan wood" = "ランブータン材"
"ramie" = "ラミー"
"raspberry wine" = "ラズベリーワイン"
"rattlesnake man venom" = "ガラガラヘビ人の毒"
"rattlesnake venom" = "ガラガラヘビの毒"
"raw adamantine" = "原精金"
"realgar" = "鶏冠石"
"red beryl" = "レッドベリル"
"red diamond" = "レッドダイヤモンド"
"red flash opal" = "レッドフラッシュオパール"
"red grossular" = "レッドグロッシュラー"
"red pyrope" = "レッドパイロープ"
"redroot dye" = "赤根染料"
"red sand" = "赤砂"
"red spinel" = "レッドスピネル"
"red tourmaline" = "レッドトルマリン"
"red zircon" = "レッドジルコン"
"reindeer cheese" = "トナカイ乳チーズ"
"reindeer's milk" = "トナカイ乳"
"resin opal" = "レジンオパール"
"rhodolite" = "ロードライト"
"rhyolite" = "流紋岩"
"rice beer" = "米ビール"
"rice flour" = "米粉"
"river spirits" = "河川スピリッツ"
"rock" = "岩石"
"rock crystal" = "水晶"
"rock nut" = "岩実"
"rock nut oil" = "岩実油"
"rock nut soap" = "岩実石鹸"
"rock salt" = "岩塩"
"rope reed" = "縄葦"
"rose gold" = "ローズゴールド"
"rose quartz" = "ローズクォーツ"
"round lime wood" = "ラウンドライム材"
"rubber wood" = "ゴムノキ材"
"rubicelle" = "ルビセル"
"ruby" = "ルビー"
"rutile" = "金紅石"
"rye beer" = "ライ麦ビール"
"rye flour" = "ライ麦粉"
"salt" = "塩"
"saltpeter" = "硝石"
"sand" = "砂"
"sand pear cider" = "ヤマナシシードル"
"sand pear wood" = "ヤマナシ材"
"sandstone" = "砂岩"
"sandy clay" = "砂質粘土"
"sandy clay loam" = "砂質埴壌土"
"sandy loam" = "砂質壌土"
"sapphire" = "サファイア"
"sard" = "サード"
"sardonyx" = "サードオニックス"
"satinspar" = "繊維石膏"
"scale" = "鱗"
"schist" = "片岩"
"schorl" = "鉄電気石"
"seed" = "種子"
"selenite" = "透石膏"
"serpentine" = "蛇紋石"
"serpent man venom" = "サーペント人の毒"
"sewer brew" = "下水酒"
"shale" = "頁岩"
"sheep cheese" = "羊乳チーズ"
"sheep's milk" = "羊乳"
"shell" = "殻"
"shell opal" = "シェルオパール"
"siliceous ooze" = "珪質軟泥"
"silk" = "絹"
"silt" = "シルト"
"silt loam" = "シルト質壌土"
"siltstone" = "シルト岩"
"silty clay" = "シルト質粘土"
"silty clay loam" = "シルト質埴壌土"
"silver" = "銀"
"sinew" = "腱"
"single-grain wheat beer" = "ヒトツブコムギビール"
"single-grain wheat flour" = "ヒトツブコムギ粉"
"skin" = "皮膚"
"slade" = "冥岩"
"slate" = "粘板岩"
"sliver dye" = "裂棘草染料"
"slush" = "泥"
"smoky quartz" = "スモーキークォーツ"
"snow" = "雪"
"soap" = "石鹸"
"soft wheat beer" = "パンコムギビール"
"soft wheat flour" = "パンコムギ粉"
"sorghum beer" = "ソルガムビール"
"sorghum flour" = "ソルガム粉"
"spelt beer" = "スペルトビール"
"spelt flour" = "スペルト粉"
"sphalerite" = "閃亜鉛鉱"
"spine" = "脊椎"
"spit" = "唾液"
"spleen tissue" = "脾臓組織"
"spore tree" = "胞子樹材"
"squid ink" = "イカの墨"
"squid man ink" = "イカ人の墨"
"star ruby" = "スタールビー"
"star sapphire" = "スターサファイア"
"steam" = "蒸気"
"sterling silver" = "スターリングシルバー"
"stibnite" = "輝安鉱"
"stomach tissue" = "胃組織"
"stoneware" = "炻器"
"strawberry wine" = "イチゴワイン"
"sunshine" = "陽光酒"
"sunstone" = "日長石"
"swamp whiskey" = "沼沢ウイスキー"
"sweat" = "汗"
"sweet potato wine" = "サツマイモワイン"
"sylvite" = "カリ岩塩"
"talc" = "滑石"
"tallow" = "獣脂"
"tanzanite" = "タンザナイト"
"tapir cheese" = "バク乳チーズ"
"tapir man cheese" = "バク人乳チーズ"
"tapir man's milk" = "バク人乳"
"tapir's milk" = "バク乳"
"tears" = "涙"
"tea wood" = "茶の木材"
"teff beer" = "テフビール"
"teff flour" = "テフ粉"
"tetrahedrite" = "黝銅鉱"
"tigereye" = "タイガーアイ"
"tiger iron" = "タイガーアイアン"
"tin" = "錫"
"tin glaze" = "錫釉"
"tomatillo wine" = "トマティーヨワイン"
"tomato wine" = "トマトワイン"
"tooth" = "歯"
"topaz" = "トパーズ"
"topazolite" = "トパゾライト"
"tower-cap" = "塔傘茸材"
"trifle pewter" = "トライフルピューター"
"tsavorite" = "ツァボライト"
"tube agate" = "チューブアゲート"
"tuber beer" = "塊根ビール"
"tunnel tube" = "隧管木材"
"turnip wine" = "カブワイン"
"turquoise" = "トルコ石"
"two-grain wheat beer" = "フタツブコムギビール"
"two-grain wheat flour" = "フタツブコムギ粉"
"two-humped camel cheese" = "フタコブラクダ乳チーズ"
"two-humped camel man cheese" = "フタコブラクダ人乳チーズ"
"two-humped camel man's milk" = "フタコブラクダ人乳"
"two-humped camel's milk" = "フタコブラクダ乳"

"unknown boiling creature substance" = "未知の沸騰生物物質"
"unknown boiling plant substance" = "未知の沸騰植物物質"
"unknown boiling substance" = "未知の沸騰物質"
"unknown creature" = "未知の生物"
"unknown creature substance" = "未知の生物物質"
"unknown frozen" = "未知の凍結物"
"unknown frozen creature" = "未知の凍結生物"
"unknown frozen creature substance" = "未知の凍結生物物質"
"unknown frozen plant" = "未知の凍結植物"
"unknown frozen plant substance" = "未知の凍結植物物質"
"unknown frozen substance" = "未知の凍結物質"
"unknown plant substance" = "未知の植物物質"
"unknown pressed frozen creature substance" = "未知の圧搾凍結生物物質"
"unknown pressed frozen plant substance" = "未知の圧搾凍結植物物質"
"unknown slush" = "未知の泥"
"unknown substance" = "未知の物質"
"variscite" = "バリサイト"
"vellum" = "ベラム"
"violet spessartine" = "バイオレットスペサルティン"
"vomit" = "吐瀉物"
"walnut wood" = "クルミ材"
"water" = "水"
"water buffalo cheese" = "スイギュウ乳チーズ"
"water buffalo's milk" = "スイギュウ乳"
"wax opal" = "ワックスオパール"
"whip vine flour" = "鞭蔓草粉"
"whip wine" = "鞭蔓草ワイン"
"white chalcedony" = "ホワイトカルセドニー"
"white jade" = "ホワイトジェード"
"white millet beer" = "白キビビール"
"white millet flour" = "白キビ粉"
"white opal" = "ホワイトオパール"
"white sand" = "白砂"
"willow" = "ヤナギ"
"wine" = "ワイン"
"wood opal" = "ウッドオパール"
"wool" = "ウール"
"yak cheese" = "ヤク乳チーズ"
"yak's milk" = "ヤク乳"
"yellow diamond" = "イエローダイヤモンド"
"yellow grossular" = "イエローグロッシュラー"
"yellow jasper" = "イエロージャスパー"
"yellow sand" = "黄砂"
"yellow spessartine" = "イエロースペサルティン"
"yellow zircon" = "イエロージルコン"
"zinc" = "亜鉛"
"rusted metal" = "錆金"
"twisting metal" = "捩金"
"dark metal" = "幽金"
"glowing metal" = "燐金"
"bright metal" = "輝金"
"pale metal" = "蒼白金"
"pock-marked metal" = "痘痕金"
"blistered metal" = "泡瘤金"
"ruddy metal" = "紅潮金"
"flickering metal" = "明滅金"
"faceted metal" = "晶面金"
"shining metal" = "煌金"
"flashing metal" = "閃光金"
"translucent metal" = "透光金"
"frosty metal" = "霜金"
"slick metal" = "滑金"
"singing metal" = "鳴金"
"black metal" = "漆黒金"
"multicolored metal" = "彩金"
"clear blue metal" = "澄青金"
"twinkling metal" = "星瞬金"
"crashing metal" = "轟金"
"blazing metal" = "炎金"
"booming metal" = "鳴轟金"
"searing metal" = "灼金"
"flowing metal" = "流金"
