base = "gems"

[[rulesets]]
[rulesets.rules]
"onyx" = "オニキス"
"onyxes" = "オニキス"
"morion" = "モリオン"
"morions" = "モリオン"
"schorl" = "鉄電気石"
"schorls" = "鉄電気石"
"lace agate" = "レースアゲート"
"lace agates" = "レースアゲート"
"blue jade" = "青翡翠"
"blue jades" = "青翡翠"
"lapis lazuli" = "ラピスラズリ"
"lapis lazulis" = "ラピスラズリ"
"prase" = "プラース"
"prases" = "プラース"
"prase opal" = "プラースオパール"
"prase opals" = "プラースオパール"
"bloodstone" = "血石"
"bloodstones" = "血石"
"moss agate" = "モスアゲート"
"moss agates" = "モスアゲート"
"moss opal" = "モスオパール"
"moss opals" = "モスオパール"
"variscite" = "バリサイト"
"variscites" = "バリサイト"
"chrysoprase" = "クリソプレーズ"
"chrysoprases" = "クリソプレーズ"
"chrysocolla" = "クリソコラ"
"chrysocollas" = "クリソコラ"
"sard" = "サード"
"sards" = "サード"
"carnelian" = "カーネリアン"
"carnelians" = "カーネリアン"
"banded agate" = "縞瑪瑙"
"banded agates" = "縞瑪瑙"
"sardonyx" = "サードオニックス"
"sardonyxes" = "サードオニックス"
"cherry opal" = "チェリーオパール"
"cherry opals" = "チェリーオパール"
"lavender jade" = "ラベンダージェイド"
"lavender jades" = "ラベンダージェイド"
"pink jade" = "ピンクジェード"
"pink jades" = "ピンクジェード"
"tube agate" = "チューブアゲート"
"tube agates" = "チューブアゲート"
"fire agate" = "ファイアアゲート"
"fire agates" = "ファイアアゲート"
"plume agate" = "プルームアゲート"
"plume agates" = "プルームアゲート"
"brown jasper" = "褐色碧玉"
"brown jaspers" = "褐色碧玉"
"picture jasper" = "ピクチャージャスパー"
"picture jaspers" = "ピクチャージャスパー"
"smoky quartz" = "スモーキークォーツ"
"smoky quartzes" = "スモーキークォーツ"
"wax opal" = "ワックスオパール"
"wax opals" = "ワックスオパール"
"wood opal" = "ウッドオパール"
"wood opals" = "ウッドオパール"
"amber opal" = "アンバーオパール"
"amber opals" = "アンバーオパール"
"gold opal" = "ゴールドオパール"
"gold opals" = "ゴールドオパール"
"citrine" = "シトリン"
"citrines" = "シトリン"
"yellow jasper" = "イエロージャスパー"
"yellow jaspers" = "イエロージャスパー"
"tigereye" = "タイガーアイ"
"tigereyes" = "タイガーアイ"
"tiger iron" = "タイガーアイアン"
"tiger irons" = "タイガーアイアン"
"sunstone" = "日長石"
"sunstones" = "日長石"
"resin opal" = "レジンオパール"
"resin opals" = "レジンオパール"
"pyrite" = "黄鉄鉱"
"pyrites" = "黄鉄鉱"
"clear tourmaline" = "クリアトルマリン"
"clear tourmalines" = "クリアトルマリン"
"gray chalcedony" = "グレーカルセドニー"
"gray chalcedonies" = "グレーカルセドニー"
"dendritic agate" = "デンドリティックアゲート"
"dendritic agates" = "デンドリティックアゲート"
"shell opal" = "シェルオパール"
"shell opals" = "シェルオパール"
"bone opal" = "ボーンオパール"
"bone opals" = "ボーンオパール"
"white chalcedony" = "ホワイトカルセドニー"
"white chalcedonies" = "ホワイトカルセドニー"
"fortification agate" = "フォルティフィケーションアゲート"
"fortification agates" = "フォルティフィケーションアゲート"
"milk quartz" = "ミルキークォーツ"
"milk quartzes" = "ミルキークォーツ"
"moonstone" = "ムーンストーン"
"moonstones" = "ムーンストーン"
"white jade" = "ホワイトジェード"
"white jades" = "ホワイトジェード"
"jasper opal" = "ジャスパーオパール"
"jasper opals" = "ジャスパーオパール"
"pineapple opal" = "パイナップルオパール"
"pineapple opals" = "パイナップルオパール"
"onyx opal" = "オニキスオパール"
"onyx opals" = "オニキスオパール"
"milk opal" = "ミルクオパール"
"milk opals" = "ミルクオパール"
"pipe opal" = "パイプオパール"
"pipe opals" = "パイプオパール"
"aventurine" = "アベンチュリン"
"aventurines" = "アベンチュリン"
"turquoise" = "トルコ石"
"turquoises" = "トルコ石"
"rose quartz" = "ローズクォーツ"
"rose quartzes" = "ローズクォーツ"
"rock crystal" = "水晶"
"rock crystals" = "水晶"
"black zircon" = "ブラックジルコン"
"black zircons" = "ブラックジルコン"
"black pyrope" = "黒苦礬柘榴石"
"black pyropes" = "黒苦礬柘榴石"
"melanite" = "メラナイト"
"melanites" = "メラナイト"
"indigo tourmaline" = "インディゴトルマリン"
"indigo tourmalines" = "インディゴトルマリン"
"blue garnet" = "青柘榴石"
"blue garnets" = "青柘榴石"
"tsavorite" = "ツァボライト"
"tsavorites" = "ツァボライト"
"green tourmaline" = "グリーントルマリン"
"green tourmalines" = "グリーントルマリン"
"demantoid" = "デマントイド"
"demantoids" = "デマントイド"
"green zircon" = "グリーンジルコン"
"green zircons" = "グリーンジルコン"
"green jade" = "グリーンジェイド"
"green jades" = "グリーンジェイド"
"heliodor" = "ヘリオドール"
"heliodors" = "ヘリオドール"
"peridot" = "ペリドット"
"peridots" = "ペリドット"
"red zircon" = "レッドジルコン"
"red zircons" = "レッドジルコン"
"red tourmaline" = "レッドトルマリン"
"red tourmalines" = "レッドトルマリン"
"red pyrope" = "レッドパイロープ"
"red pyropes" = "レッドパイロープ"
"almandine" = "アルマンディン"
"almandines" = "アルマンディン"
"red grossular" = "レッドグロッシュラー"
"red grossulars" = "レッドグロッシュラー"
"pink tourmaline" = "ピンクトルマリン"
"pink tourmalines" = "ピンクトルマリン"
"red beryl" = "レッドベリル"
"red beryls" = "レッドベリル"
"fire opal" = "ファイアオパール"
"fire opals" = "ファイアオパール"
"rhodolite" = "ロードライト"
"rhodolites" = "ロードライト"
"purple spinel" = "紫スピネル"
"purple spinels" = "紫スピネル"
"alexandrite" = "アレキサンドライト"
"alexandrites" = "アレキサンドライト"
"tanzanite" = "タンザナイト"
"tanzanites" = "タンザナイト"
"morganite" = "モルガナイト"
"morganites" = "モルガナイト"
"violet spessartine" = "バイオレットスペサルティン"
"violet spessartines" = "バイオレットスペサルティン"
"pink garnet" = "ピンクガーネット"
"pink garnets" = "ピンクガーネット"
"kunzite" = "クンツァイト"
"kunzites" = "クンツァイト"
"cinnamon grossular" = "ヘソナイト"
"cinnamon grossulars" = "ヘソナイト"
"honey yellow beryl" = "ハニーイエローベリル"
"honey yellow beryls" = "ハニーイエローベリル"
"jelly opal" = "ジェリーオパール"
"jelly opals" = "ジェリーオパール"
"brown zircon" = "ブラウンジルコン"
"brown zircons" = "ブラウンジルコン"
"yellow zircon" = "イエロージルコン"
"yellow zircons" = "イエロージルコン"
"golden beryl" = "ゴールデンベリル"
"golden beryls" = "ゴールデンベリル"
"yellow spessartine" = "イエロースペサルティン"
"yellow spessartines" = "イエロースペサルティン"
"topaz" = "トパーズ"
"topazes" = "トパーズ"
"topazolite" = "トパゾライト"
"topazolites" = "トパゾライト"
"yellow grossular" = "イエローグロッシュラー"
"yellow grossulars" = "イエローグロッシュラー"
"rubicelle" = "ルビセル"
"rubicelles" = "ルビセル"
"clear garnet" = "クリアガーネット"
"clear garnets" = "クリアガーネット"
"goshenite" = "ゴシェナイト"
"goshenites" = "ゴシェナイト"
"cat's eye" = "キャッツアイ"
"cat's eyes" = "キャッツアイ"
"clear zircon" = "クリアジルコン"
"clear zircons" = "クリアジルコン"
"amethyst" = "アメシスト"
"amethysts" = "アメシスト"
"aquamarine" = "アクアマリン"
"aquamarines" = "アクアマリン"
"red spinel" = "レッドスピネル"
"red spinels" = "レッドスピネル"
"chrysoberyl" = "クリソベリル"
"chrysoberyls" = "クリソベリル"
"precious fire opal" = "プレシャスファイアオパール"
"precious fire opals" = "プレシャスファイアオパール"
"red flash opal" = "レッドフラッシュオパール"
"red flash opals" = "レッドフラッシュオパール"
"black opal" = "ブラックオパール"
"black opals" = "ブラックオパール"
"white opal" = "ホワイトオパール"
"white opals" = "ホワイトオパール"
"crystal opal" = "クリスタルオパール"
"crystal opals" = "クリスタルオパール"
"claro opal" = "クラロオパール"
"claro opals" = "クラロオパール"
"levin opal" = "レヴィンオパール"
"levin opals" = "レヴィンオパール"
"harlequin opal" = "ハーレクインオパール"
"harlequin opals" = "ハーレクインオパール"
"pinfire opal" = "ピンファイアオパール"
"pinfire opals" = "ピンファイアオパール"
"bandfire opal" = "バンドファイアオパール"
"bandfire opals" = "バンドファイアオパール"
"light yellow diamond" = "ライトイエローダイヤモンド"
"light yellow diamonds" = "ライトイエローダイヤモンド"
"faint yellow diamond" = "フェイントイエローダイヤモンド"
"faint yellow diamonds" = "フェイントイエローダイヤモンド"
"emerald" = "エメラルド"
"emeralds" = "エメラルド"
"ruby" = "ルビー"
"rubies" = "ルビー"
"sapphire" = "サファイア"
"sapphires" = "サファイア"
"clear diamond" = "クリアダイヤモンド"
"clear diamonds" = "クリアダイヤモンド"
"red diamond" = "レッドダイヤモンド"
"red diamonds" = "レッドダイヤモンド"
"green diamond" = "グリーンダイヤモンド"
"green diamonds" = "グリーンダイヤモンド"
"blue diamond" = "ブルーダイヤモンド"
"blue diamonds" = "ブルーダイヤモンド"
"yellow diamond" = "イエローダイヤモンド"
"yellow diamonds" = "イエローダイヤモンド"
"black diamond" = "ブラックダイヤモンド"
"black diamonds" = "ブラックダイヤモンド"
"star sapphire" = "スターサファイア"
"star sapphires" = "スターサファイア"
"star ruby" = "スタールビー"
"star rubies" = "スタールビー"
