base = "items"

[[rulesets]]
[rulesets.rules]
"{%item_designation:main}" = "{%item_designation:main}"

[[rulesets]]
name = "main"
[rulesets.rules]
"{anvil}" = "{anvil}"
"{bed}" = "{bed}"
"{table}" = "{table}"
"{cabinet}" = "{cabinet}"
"{bookcase}" = "{bookcase}"
"{armorstand}" = "{armorstand}"
"{weaponrack}" = "{weaponrack}"
"{displaycase}" = "{displaycase}"
"{pedestal}" = "{pedestal}"
