base = "items"

[[rulesets]]
[rulesets.rules]
"{%item_designation:main}" = "{%item_designation:main}"

[[rulesets]]
name = "main"
[rulesets.rules]
"{anvil}" = "{anvil}"
"{bed}" = "{bed}"
"{table}" = "{table}"
"{cabinet}" = "{cabinet}"
"{bookcase}" = "{bookcase}"
"{armorstand}" = "{armorstand}"
"{weaponrack}" = "{weaponrack}"
"{displaycase}" = "{displaycase}"
"{pedestal}" = "{pedestal}"
"{animaltrap}" = "{animaltrap}"
"{bucket}" = "{bucket}"
"{hive}" = "{hive}"
"{millstone}" = "{millstone}"
"{minecart}" = "{minecart}"
"{nestbox}" = "{nestbox}"
"{pot}" = "{pot}"
"{quern}" = "{quern}"
"{stepladder}" = "{stepladder}"
"{wheelbarrow}" = "{wheelbarrow}"
"{blocks}" = "{blocks}"
"{pipe_section}" = "{pipe_section}"
"{scrollroller}" = "{scrollroller}"
"{splint}" = "{splint}"
"{floodgate}" = "{floodgate}"
"{window}" = "{window}"
"{traction_bench}" = "{traction_bench}"
